### ISSUE TITLE
It's Not Quantizing

### ISSUE THREAD

**Issue by midiguru** [Ahornberg/Ahornberg-Microtonal#9]
This is a fine idea for a module! But in the 1.0.1 Windows build, it doesn't actually quantize. By adjusting the input voltage a bit at a time, I can produce a huge variety of microtones, even when it's set to 12ed2.

**Comment by midiguru** [comment]
To be more specific, it seems to be doing division on the input values -- probably the division is correct. But it's not producing a stepped output, so it's not useful. It isn't doing anything that Nysthi ConstAddMult doesn't do.

**Comment by Ahornberg** [comment]
This module isn't a quantizer, it's an attenuator.

**Comment by midiguru** [comment]
If it doesn't quantize, the business of dividing some interval (such as an octave) into equal divisions makes no sense whatever. You're not accomplishing anything.

**Comment by Ahornberg** [comment]
The business of this module is not to quantize, but to shrink or stretch already quantized pitch-CV. I didn't implement a quantizer directly into my module because I want to preserve all glissandi in the pitch-CV signal.

On the other hand, a continuous pitch-CV signal needs to be quantized before running it through my module to achieve microtonal pitch-CV steps. For your use-case it's necessary to use a quantizer (e.g. the QNT module) before my module.

And here's the way it works for me: I play on a MIDI keyboard and run the V/OCT values from the core MIDI-CV module through my module, which is set to e.g. 33ed4 (my favourite equal tuning). The same can be achieved by running pitch-CV from a sequencer module through my module.

**Comment by midiguru** [comment]
I guess that makes sense. I tried running a polyphonic output from JW NoteSeq into a Split module, then through four channels of your module, and then back through a Merge, and got the expected result -- chords in whatever equal tuning I choose. Thanks for explaining it!
